name: DotaMinecraft
main: com.gmail.scyntrus.dotaminecraft.DotaMinecraft
author: Scyntrus
version: 2.12
depend: [Multiverse-Core]
commands:
    dota:
        description: Dota commands
        usage: "/dota [join|restart|score|recall]"
    t:
        description: Team chat
        usage: "/t MESSAGE"
permissions:
    dota.restart:
        description: Allows you to restart the game when it is finished
        default: true
    dota.forcerestart:
        description: Allows you to restart the game at any time
        default: false
    dota.chooseteam:
        description: Allows you to choose a team to join
        default: false